services:
  - type: web
    name: ai-marketing-backend
    env: python
    runtime: python-3.11.8
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt && python migrate.py"
    startCommand: "python main.py"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ai-marketing-db
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: CORS_ORIGINS
        value: "https://graceful-truffle-fa4c90.netlify.app"
      - key: OPENROUTER_API_KEY_1
        value: "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"
      - key: OPENROUTER_API_KEY_2
        value: "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"
      - key: OPENROUTER_API_KEY_3
        value: "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"
      - key: OPENROUTER_API_KEY_4
        value: "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"
      - key: OPENROUTER_API_KEY_5
        value: "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"
      - key: OPENROUTER_API_KEY_6
        value: "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"
      - key: UPLOAD_DIR
        value: "uploads"
      - key: MAX_FILE_SIZE
        value: "10485760"
      - key: ALLOWED_IMAGE_EXTENSIONS
        value: "jpg,jpeg,png,webp"
      - key: REDIS_URL
        value: "redis://localhost:6379/0"
      - key: OPENROUTER_BASE_URL
        value: "https://openrouter.ai/api/v1/chat/completions"
      - key: OPENROUTER_SITE_NAME
        value: "AI Marketing Platform"
      - key: OPENROUTER_SITE_URL
        value: "https://ai-marketing-app-bmvz.onrender.com"
      - key: APP_NAME
        value: "AI Marketing Platform"
      - key: APP_VERSION
        value: "1.0.0"
    
databases:
  - name: ai-marketing-db
    databaseName: ai_marketing_app
    user: ai_marketing_app_user