services:
  - type: web
    name: ai-marketing-backend
    env: python
    buildCommand: "pip install -r requirements.txt && alembic upgrade head"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ai-marketing-db
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: CORS_ORIGINS
        value: "https://ai-marketing-platform.netlify.app"
    
databases:
  - name: ai-marketing-db
    databaseName: ai_marketing_app
    user: ai_marketing_app_user