services:
  - type: web
    name: ai-marketing-backend
    env: python
    runtime: python-3.11
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ai-marketing-db
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: CORS_ORIGINS
        value: "https://graceful-truffle-fa4c90.netlify.app,http://localhost:3000"
      - key: OPENROUTER_API_KEY_1
        sync: false
      - key: OPENROUTER_API_KEY_2
        sync: false
      - key: OPENROUTER_API_KEY_3
        sync: false
      - key: OPENROUTER_API_KEY_4
        sync: false
      - key: OPENROUTER_API_KEY_5
        sync: false
      - key: OPENROUTER_API_KEY_6
        sync: false
      - key: OPENROUTER_SITE_URL
        value: "https://ai-marketing-app-bmvz.onrender.com"
      - key: UPLOAD_DIR
        value: "uploads"
      - key: MAX_FILE_SIZE
        value: "10485760"
      - key: ALLOWED_IMAGE_EXTENSIONS
        value: "jpg,jpeg,png,webp"
      - key: OPENROUTER_BASE_URL
        value: "https://openrouter.ai/api/v1/chat/completions"
      - key: OPENROUTER_SITE_NAME
        value: "AI Marketing Platform"
      - key: APP_NAME
        value: "AI Marketing Platform"
      - key: APP_VERSION
        value: "1.0.0"

databases:
  - name: ai-marketing-db
    databaseName: ai_marketing_app
    user: ai_marketing_app_user